questions/urls.py
from django.urls import path

# 実験用
from django.views.generic import TemplateView
from . import views

app_name = 'questions'

urlpatterns = [
    path('input/', views.QuestionInput.as_view(), name='question_input'),  # 質問記入画面
    path('<int:question_pk>/', views.QuestionDetail.as_view(), name='question_detail'),  # 質問表示画面
    path('<int:question_pk>/edit/', views.QuestionEdit.as_view(), name='question_edit'),  # 質問編集画面

    path('<int:question_pk>/answer/input/', views.AnswerInput.as_view(), name='answer_input'),  # 答え表示
    path('<int:question_pk>/answer/<int:answer_pk>/edit/',
         views.AnswerEdit.as_view(), name='answer_edit'),  # 答え編集

    path('<int:question_pk>/answer/<int:answer_pk>/comment/<int:comment_pk>/edit/',
         views.CommentEdit.as_view(), name='comment_edit'),# コメント編集画面
    # jsonでtag一覧を得るため。
    path('api/tags/get/', views.api_tags_get, name='api_tags_get')
]

tags/urls.py
from django.urls import path
from . import views

# 実験用
from django.views.generic import TemplateView

app_name = 'tags'

urlpatterns = [
    path('', views.TagListView.as_view(), name='tag_list'),  # タグ一覧メニュー
    path('<int:tag_pk>/', views.TagDetailView.as_view(), name='tag_detail'),# タグ詳細
    path('<int:tag_pk>/<str:tag_nav>/', views.TagDetailView.as_view(), name='tag_nav'), # 詳細の中のナビゲーション部分
]

users/urls.py
from django.urls import path
from . import views
# 実験用
from django.views.generic import TemplateView

app_name = 'users'

urlpatterns = [
    path('setting/profile/', views.ProfileSetting.as_view(), name='profile_setting'),  # プロフィール設定
    path('setting/leave-confirm/', views.LeaveConfirm.as_view(), name='leave_confirm'),  # 退会確認

    path('profile/<int:user_pk>', views.ProfileDetail.as_view(), name='profile_detail'),  # プロフィール詳細
    path('profile/<int:user_pk>/<str:profile_nav>/', views.ProfileDetail.as_view(),
         name='profile_nav'),

    path('<int:user_pk>/connection/', views.Connection.as_view(), name='connection'),

    path('ranking/', views.RankingList.as_view(), name='ranking_list'),
]

questions/models.py
from django.db import models
# markdown用
from django.utils.safestring import mark_safe
from markdown import markdown

from tags.models import Tag
from django.contrib.auth import get_user_model


# questionのモデル
class Question(models.Model):
    subject = models.CharField(max_length=20)
    message = models.TextField(max_length=4000)
    created_at = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    # タグを削除できないようにProtectと指定している。
    tag = models.ManyToManyField(Tag, related_name='question_tag', verbose_name='タグ全て', )

    starter = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True)
    views = models.PositiveIntegerField(default=0)
    has_bestAnser = models.BooleanField(default=False)

    def __str__(self):
        return self.subject

    def get_message_as_markdown(self):
        return mark_safe(markdown(self.message, safe_mode='escape'))

    # 回答数を簡単に得る
    def get_answers_count(self):
        return Answer.objects.filter(question=self).count()


class Answer(models.Model):
    message = models.TextField(verbose_name="回答", max_length=4000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    is_bestAnswer = models.BooleanField(default=False)

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True)


class Comment(models.Model):
    message = models.TextField(verbose_name="コメント",  max_length=2000)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True)

questions/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.urls import reverse_lazy

from questions.widgets import SuggestWidget
from .models import Question, Comment, Answer


class QuestionInputForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'tag', 'message']
        widgets = {
            'tag': SuggestWidget(attrs={'data-url': reverse_lazy('questions:api_tags_get')}),
        }

    def clean_tag(self):
        tag = self.cleaned_data['tag']
        if len(tag) > 5:
            raise ValidationError("タグが五つ以上設定されています。")
        return tag

# 返信フォーム
class AnswerInputForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['message']


# コメントフォーム
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message']


questions/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, UpdateView
from django.contrib import messages

from questions.forms import QuestionInputForm, CommentForm, AnswerInputForm
from tags.models import Tag
from .models import Question, Answer, Comment
from django.contrib.auth import get_user_model
from django.db.models import Count

from django.views import View
from django.views.generic import FormView
from django.views.generic.detail import DetailView
from django.utils import timezone


# 特別にルートのアプリケーションのviewをquestionsに入れる。
class QuestionList(ListView):
    model = Question
    paginate_by = 10
    template_name = 'homes/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['home_nav'] = self.kwargs.get("home_nav")
        users = get_user_model().objects.all().order_by('-score')
        context['users'] = users
        context['user'] = self.request.user
        if not self.request.user.is_anonymous:
            i = 0
            for index, u in enumerate(users):
                if u == self.request.user:
                    i = index
                    break
            context['user_index'] = i + 1
        return context

    def get_queryset(self):
        queryset = None
        if self.kwargs.get("home_nav") != 'active':
            queryset = Question.objects.all().order_by('-created_at').annotate(replies=Count('answer'))
        else:
            queryset = Question.objects.all().order_by('-last_updated').annotate(replies=Count('answer'))
        return queryset


@method_decorator(login_required, name='dispatch')
class QuestionInput(FormView):
    template_name = 'questions/question_input.html'
    form_class = QuestionInputForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        new_question = form.save(commit=False)
        new_question.starter = self.request.user
        new_question.save()
        form.save_m2m()

        self.request.user.score += 1
        self.request.user.save()
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class QuestionDetail(View):

    def get(self, request, *args, **kwargs):
        question_pk = self.kwargs.get("question_pk")
        question = Question.objects.get(pk=question_pk)
        session_key = 'viewed_topic_{}'.format(question_pk)
        if not request.session.get(session_key, False):
            question.views += 1  # 閲覧数
            question.save()
            request.session[session_key] = True

        return render(request, 'questions/question_detail.html', {
            'question': Question.objects.get(pk=self.kwargs.get("question_pk")),
            'comment_form': CommentForm(),
            'user': self.request.user
        })

    def post(self, request, *args, **kwargs):
        question_pk = self.kwargs.get("question_pk")
        question = Question.objects.get(pk=question_pk)

        # ベストアンサー関連のリクエスト
        if 'best' in request.POST:
            best_answer = Answer.objects.get(pk=request.POST["best"])
            best_answer.is_bestAnser = True
            question.has_bestAnser = True
            best_answer.save()
            question.save()
            user = best_answer.created_by
            user.score += 3
            user.save()
            return redirect('questions:question_detail', question_pk=question_pk)
        elif 'delbest' in request.POST:
            best_answer = Answer.objects.get(pk=request.POST["delbest"])
            best_answer.is_bestAnser = False
            question.has_bestAnser = False
            best_answer.save()
            question.save()
            return redirect('questions:question_detail', question_pk=question_pk)

        # 削除関連のリクエスト
        elif 'delete_question' in request.POST:
            del_question = Question.objects.get(pk=request.POST["delete_question"])
            del_question.delete()
            return redirect("home")
        elif 'delete_answer' in request.POST:
            del_answer = Answer.objects.get(pk=request.POST["delete_answer"])
            del_answer.delete()
            return redirect('questions:question_detail', question_pk=question_pk)
        elif 'delcomment' in request.POST:
            delcomment = Comment.objects.get(pk=request.POST["delcomment"])
            delcomment.delete()
            return redirect('questions:question_detail', question_pk=question_pk)

        # コメントのform
        else:
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                com_answer = Answer.objects.get(pk=request.POST["comment"])
                comment.answer = com_answer
                comment.created_by = request.user
                comment.save()
                com_answer.save()
            return redirect('questions:question_detail', question_pk=question_pk)


@method_decorator(login_required, name='dispatch')
class QuestionEdit(UpdateView):
    model = Question
    fields = ('subject', 'tag1', 'tag2', 'message',)
    template_name = 'questions/question_edit.html'
    pk_url_kwarg = 'question_pk'

    # 作った人のみアクセス可
    def get_object(self, *args, **kwargs):
        obj = super(QuestionEdit, self).get_object(*args, **kwargs)
        if not obj.starter == self.request.user:
            raise Http404
        return obj

    # 適切なpostだったらインスタンスを保存。
    def form_valid(self, form):
        question = form.save(commit=False)
        question.last_updated = timezone.now()
        question.tag.clear()
        question.tag.add(question.tag1)
        if question.tag2 is not None:
            question.tag.add(question.tag2)
        question.save()
        return redirect('questions:question_detail', question_pk=self.kwargs.get("question_pk"))


@method_decorator(login_required, name='dispatch')
class AnswerInput(FormView):
    template_name = 'questions/answer_input.html'
    form_class = AnswerInputForm

    def get_success_url(self):
        return reverse_lazy('questions:question_detail',
                            kwargs={'question_pk': self.kwargs.get("question_pk")})

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['question'] = Question.objects.get(pk=self.kwargs.get("question_pk"))
        return ctx

    def form_valid(self, form):
        answer_form = form.save(commit=False)
        question = Question.objects.get(pk=self.kwargs.get("question_pk"))
        answer_form.question = question
        answer_form.created_by = self.request.user

        answer_form.save()
        question.save()

        self.request.user.score += 1
        self.request.user.save()
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class AnswerEdit(UpdateView):
    model = Answer
    fields = ('message',)
    template_name = 'questions/answer_edit.html'
    pk_url_kwarg = 'answer_pk'

    def get_object(self, *args, **kwargs):
        obj = super(AnswerEdit, self).get_object(*args, **kwargs)
        if not obj.created_by == self.request.user:
            raise Http404
        return obj

    def form_valid(self, form):
        answer = form.save(commit=False)
        answer.updated_by = self.request.user
        answer.updated_at = timezone.now()
        answer.save()
        return redirect('questions:question_detail', question_pk=self.kwargs.get("question_pk"))


@method_decorator(login_required, name='dispatch')
class CommentEdit(UpdateView):
    model = Comment
    fields = ('message',)
    template_name = 'questions/comment_edit.html'
    pk_url_kwarg = 'comment_pk'

    def get_object(self, *args, **kwargs):
        obj = super(CommentEdit, self).get_object(*args, **kwargs)
        if not obj.created_by == self.request.user:
            raise Http404
        return obj

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.updated_at = timezone.now()
        comment.save()
        return redirect('questions:question_detail', question_pk=self.kwargs.get("question_pk"))


def api_tags_get(request):
    keyword = request.GET.get('keyword')
    if keyword:
        tag_list = [{'pk': tag.pk, 'name': str(tag)} for tag in Tag.objects.filter(name__istartswith=keyword)]
        count = 0
        neo_tag_list = []
        for t in tag_list:
            count += 1
            neo_tag_list.append(t)
            if count > 5:
                break
        tag_list = neo_tag_list
    else:
        tag_list = []
    return JsonResponse({'object_list': tag_list})


templates/questions/question_detail_part/answer.html
<div class="m-2">
    {% if answer.is_bestAnser %}
    <div class="alert-danger" style="display: inline-block;" role="alert">ベストアンサー</div>
    {% else %}
    <div class="alert-secondary" style="display: inline-block;" role="alert">回答</div>
    {% endif %}

    <div class="m-2" style="word-wrap: break-word;">
        {{ answer.message }}
    </div>
    <div style="display: flex; align-items: center">
        <div style="margin-left: auto">
            <small class="text-muted mr-1">{{ answer.created_at }}</small>
            <a href="{% url 'users:profile_detail' user_pk=answer.created_by.id %}">
                <img class="mr-1" src="{{ answer.created_by.icon.url }}" alt="{{ answer.created_by.username }}"
                     style="width: 30px;"/>
            </a>
            <a href="{% url 'users:profile_detail' user_pk=answer.created_by.id %}">
                <span>{{ answer.created_by.username }}</span>
            </a>
        </div>
    </div>
</div>

<div class="mt-1" style="display: flex; align-items: flex-start;">
    {% if answer.created_by == user %}
    <a href="{% url 'questions:answer_edit' question_pk=answer.question.pk answer_pk=answer.pk %}"
       class="btn btn-secondary btn-sm mr-2" role="button">編集</a>
    <form method="post" class="mr-2" novalidate>
        {% csrf_token %}
        <button type="submit" name="delete_answer" value="{{ answer.id }}" class="btn btn-danger btn-sm" role="button">
            回答削除
        </button>
    </form>
    {% endif %}
    {% if user == question.starter %}
    {% if not question.has_bestAnser %}
    <form method="post">
        {% csrf_token %}
        <button type="submit" name="best" value="{{ answer.id }}" class="btn btn-outline-danger btn-sm">
            ベストアンサー
        </button>
    </form>
    {% endif %}

    {% if answer.is_bestAnswer %}
    <form method="post">
        {% csrf_token %}
        <button type="submit" name="delbest" value="{{ answer.id }}" class="btn btn-outline-danger btn-sm">
            ベストアンサーを解除
        </button>
    </form>
    {% endif %}
    {% endif %}
</div>

templates/questions/question_detail_part/comment.html
{% load widget_tweaks %}

<div class="mb-5" style="margin-left:50%;">
    <button class="btn btn-outline-secondary btn-sm" type="button" data-toggle="collapse"
            data-target="#collapse{{ answer.id }}"
            aria-expanded="false" aria-controls="collapseExample">
        コメント一覧
    </button>
    <hr>
    <div class="collapse" id="collapse{{ answer.id }}">
        {% for comment in answer.comment_set.all %}
        <div class="m-2" style="word-wrap: break-word;">
            {{ comment.message }}
        </div>
        {% if comment.created_by == user %}
        <form method="post" class="mr-2" novalidate>
            {% csrf_token %}
            <a href="{% url 'questions:comment_edit' answer.question.pk answer.pk comment.pk %}" class="btn btn-secondary btn-sm"
               role="button">編集</a>
            <button type="submit" name="delcomment" value="{{ comment.id }}" class="btn btn-danger btn-sm"
                    role="button">コメント削除
            </button>
        </form>
        {% endif %}
        <div style="display: flex; align-items: center">
            <div style="margin-left: auto">
                <small class="text-muted mr-1">{{ comment.created_at }}</small>
                <a href="{% url 'users:profile_detail' user_pk=comment.created_by.pk %}">
                    <img class="mr-1" src="{{ comment.created_by.icon.url }}" style="width: 30px;"/>
                </a>
                <a href="{% url 'users:profile_detail' user_pk=comment.created_by.pk %}">
                    <span>{{ comment.created_by.username }}</span>
                </a>
            </div>
        </div>
        <hr>
        {% endfor %}

        <form method="post" class="mb-4" novalidate>
            {% csrf_token %}
            <div class="form-group row m-2">
                <div class="col-sm-12">
                    {% if comment_form.is_bound %}
                    {% if comment_form.message.errors %}
                    {% render_field comment_form.message class="form-control is-invalid" placeholder="コメントをしてください" %}
                    {% for error in comment_form.message.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                    {% endfor %}
                    {% else %}
                    {% render_field comment_form.message class="form-control is-valid" placeholder="コメントをしてください" %}
                    {% endif %}
                    {% else %}
                    {% render_field comment_form.message class="form-control" placeholder="コメントをしてください" %}
                    {% endif %}
                </div>
            </div>
            <button class="btn btn-outline-primary btn-sm" name="comment" value="{{ answer.id }}" type="submit">
                コメントする
            </button>
        </form>

    </div>
</div>

templates/questions/question_detail_part/jumbotron.html
<div class="container">
    <div style="border-bottom: solid grey 1px; padding-bottom: 4px;">
        {% for tag in question.tag.all %}
        <a class="badge badge-pill badge-primary" href="{% url 'tags:tag_detail' tag.pk %}">
            <span style="color: white;">{{ tag.name }}</span>
        </a>
        {% endfor %}
    </div>
    <div style="display:flex;">
        <div style="display:flex; flex-direction: column;">
            <h5 class="py-4">{{ question.subject }}</h5>
            <div style="display: flex;">
                {% if question.has_bestAnser %}
                <p class="pr-4" style="color: orangered;">解決済み</p>
                {% else %}
                <p class="pr-4" style="color: gray;">受付中</p>
                {% endif %}
                <span class="pr-4">回答 <span style="color: orangered;">{{ question.answer.count }}</span> 件</span>
                <span class="text-muted">投稿 {{ question.last_updated }}</span>
            </div>
        </div>

        <div class="pr-2"
             style="display:flex; flex-direction: column; align-items:center; margin: auto 0 auto auto; ">
            <p>View {{ question.views }}</p>
            <div style="display:flex; align-items: center;">
                <a href="{% url 'users:profile_detail' user_pk=question.starter.pk %}">
                    <img class="pr-1" src="{{ question.starter.icon.url }}" style="width: 30px;"/>
                </a>
                <a href="{% url 'users:profile_detail' user_pk=question.starter.pk %}">
                    <span class="pr-1">{{ question.starter }}</span>
                </a>
                <small>Score {{ question.starter.score }}</small>
            </div>
        </div>
    </div>
</div>

templates/questions/question_detail_part/question.html
<div class="mb-4">
    <div class="mb-2 pb-3" style="word-wrap: break-word;">
        {{ question.get_message_as_markdown }}
    </div>
    {% if question.starter == user %}
    <form method="post" class="mb-4" novalidate>
        {% csrf_token %}
        <a href="{% url 'questions:question_edit' question.pk %}" class="btn btn-secondary btn-sm" role="button">編集</a>
        <button type="submit" name="delete_question" value="{{ question.id }}" class="btn btn-danger btn-sm"
                role="button">質問削除
        </button>
    </form>
    {% endif %}
    <hr>
</div>