helps/urls.py
from django.urls import path

from helps.views import HelpView

app_name = 'helps'

urlpatterns = [
    path('', HelpView.as_view(), name='help'),
]

questions/urls.py
from django.urls import path

# 実験用
from django.views.generic import TemplateView
from . import views

app_name = 'questions'

urlpatterns = [
    path('input/', views.QuestionInput.as_view(), name='question_input'),  # 質問記入画面
    path('<int:question_pk>/', views.QuestionDetail.as_view(), name='question_detail'),  # 質問表示画面
    path('<int:question_pk>/edit/', views.QuestionEdit.as_view(), name='question_edit'),  # 質問編集画面

    path('<int:question_pk>/answer/input/', views.AnswerInput.as_view(), name='answer_input'),  # 答え表示
    path('<int:question_pk>/answer/<int:answer_pk>/edit/',
         views.AnswerEdit.as_view(), name='answer_edit'),  # 答え編集

    path('<int:question_pk>/answer/<int:answer_pk>/comment/<int:comment_pk>/edit/',
         views.CommentEdit.as_view(), name='comment_edit'),# コメント編集画面
    # jsonでtag一覧を得るため。
    path('api/tags/get/', views.api_tags_get, name='api_tags_get')
]

tags/urls.py
from django.urls import path
from . import views

# 実験用
from django.views.generic import TemplateView

app_name = 'tags'

urlpatterns = [
    path('', views.TagListView.as_view(), name='tag_list'),  # タグ一覧メニュー
    path('<int:tag_pk>/', views.TagDetailView.as_view(), name='tag_detail'),# タグ詳細
    path('<int:tag_pk>/<str:tag_nav>/', views.TagDetailView.as_view(), name='tag_nav'), # 詳細の中のナビゲーション部分
]

users/urls.py
from django.urls import path
from . import views
# 実験用
from django.views.generic import TemplateView

app_name = 'users'

urlpatterns = [
    path('setting/profile/', views.ProfileSetting.as_view(), name='profile_setting'),  # プロフィール設定
    path('setting/leave-confirm/', views.LeaveConfirm.as_view(), name='leave_confirm'),  # 退会確認

    path('profile/<int:user_pk>', views.ProfileDetail.as_view(), name='profile_detail'),  # プロフィール詳細
    path('profile/<int:user_pk>/<str:profile_nav>/', views.ProfileDetail.as_view(),
         name='profile_nav'),

    path('<int:user_pk>/connection/', views.Connection.as_view(), name='connection'),

    path('ranking/', views.RankingList.as_view(), name='ranking_list'),
]

templates/common/base.html
{% load static %}
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}nerorei[ネロレイ] | 学習特化型Q&Aサイト{% endblock %}</title>
    {% block meta %}{% endblock %}

    <link rel="shortcut icon" type="image/png"
          href="{% static 'images/favicon.ico' %}"/>

    {# --- CDN --- #}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">

    <!--simpleMdn-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>

    {# --- css --- #}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block stylesheet %}{% endblock %}
</head>

<body>

{% include './nav.html' %}

<main>
    {% block content %}{% endblock %}
</main>

<script
        src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
{% block javascript %}{% endblock %}
</body>

</html>

templates/common/form.html
{% load widget_tweaks %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
    {% endfor %}
  </div>
{% endif %}

{% for field in form %}
  <div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">
        {{ field.help_text }}
      </small>
    {% endif %}
  </div>
{% endfor %}

templates/common/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">nerorei</a>
        <div>
            <a href="{% url 'questions:question_input' %}" class="btn btn-primary m-2">質問ページへ</a>
        </div>
        <div>
            <a class="nav-link" href="{% url 'helps:help' %}">
                ヘルプ
            </a>
        </div>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu"
                aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="mainMenu">
            {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                        <a class="dropdown-item" href="{% url 'users:profile_detail' user_pk=user.id %}">マイアカウント</a>
                        <a class="dropdown-item" href="{% url 'users:profile_setting' %}">プロフィール設定</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'account_logout' %}">Log out</a>
                    </div>
                </li>
            </ul>
            {% else %}
            <form class="form-inline ml-auto my-auto">
                <a href="{% url 'account_login' %}" class="btn btn-outline-secondary">Log in</a>
                <a href="{% url 'account_signup' %}" class="btn btn-primary ml-2">Sign up</a>
            </form>
            {% endif %}
        </div>
    </div>
</nav>

templates/common/pagination.html
{% if is_paginated %}
  <nav aria-label="Topics pagination" class="mb-4">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Previous</span>
        </li>
      {% endif %}

      {% for page_num in paginator.page_range %}
        {% if page_obj.number == page_num %}
          <li class="page-item active">
            <span class="page-link">
              {{ page_num }}
              <span class="sr-only">(current)</span>
            </span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Next</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}