questions/urls.py
from django.urls import path

# 実験用
from django.views.generic import TemplateView
from . import views

app_name = 'questions'

urlpatterns = [
    path('input/', views.QuestionInput.as_view(), name='question_input'),  # 質問記入画面
    path('<int:question_pk>/', views.QuestionDetail.as_view(), name='question_detail'),  # 質問表示画面
    path('<int:question_pk>/edit/', views.QuestionEdit.as_view(), name='question_edit'),  # 質問編集画面

    path('<int:question_pk>/answer/input/', views.AnswerInput.as_view(), name='answer_input'),  # 答え表示
    path('<int:question_pk>/answer/<int:answer_pk>/edit/',
         views.AnswerEdit.as_view(), name='answer_edit'),  # 答え編集

    path('<int:question_pk>/answer/<int:answer_pk>/comment/<int:comment_pk>/edit/',
         views.CommentEdit.as_view(), name='comment_edit'),# コメント編集画面
    # jsonでtag一覧を得るため。
    path('api/tags/get/', views.api_tags_get, name='api_tags_get')
]

tags/urls.py
from django.urls import path
from . import views

# 実験用
from django.views.generic import TemplateView

app_name = 'tags'

urlpatterns = [
    path('', views.TagListView.as_view(), name='tag_list'),  # タグ一覧メニュー
    path('<int:tag_pk>/', views.TagDetailView.as_view(), name='tag_detail'),# タグ詳細
    path('<int:tag_pk>/<str:tag_nav>/', views.TagDetailView.as_view(), name='tag_nav'), # 詳細の中のナビゲーション部分
]

users/urls.py
from django.urls import path
from . import views
# 実験用
from django.views.generic import TemplateView

app_name = 'users'

urlpatterns = [
    path('setting/profile/', views.ProfileSetting.as_view(), name='profile_setting'),  # プロフィール設定
    path('setting/leave-confirm/', views.LeaveConfirm.as_view(), name='leave_confirm'),  # 退会確認

    path('profile/<int:user_pk>', views.ProfileDetail.as_view(), name='profile_detail'),  # プロフィール詳細
    path('profile/<int:user_pk>/<str:profile_nav>/', views.ProfileDetail.as_view(),
         name='profile_nav'),

    path('<int:user_pk>/connection/', views.Connection.as_view(), name='connection'),

    path('ranking/', views.RankingList.as_view(), name='ranking_list'),
]

questions/models.py
from django.db import models
# markdown用
from django.utils.safestring import mark_safe
from markdown import markdown

from tags.models import Tag
from django.contrib.auth import get_user_model


# questionのモデル
class Question(models.Model):
    subject = models.CharField(max_length=20)
    message = models.TextField(max_length=4000)
    created_at = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    # タグを削除できないようにProtectと指定している。
    tag = models.ManyToManyField(Tag, related_name='question_tag', verbose_name='タグ全て', )

    starter = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True)
    views = models.PositiveIntegerField(default=0)
    has_bestAnser = models.BooleanField(default=False)

    def __str__(self):
        return self.subject

    def get_message_as_markdown(self):
        return mark_safe(markdown(self.message, safe_mode='escape'))

    # 回答数を簡単に得る
    def get_answers_count(self):
        return Answer.objects.filter(question=self).count()


class Answer(models.Model):
    message = models.TextField(verbose_name="回答", max_length=4000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    is_bestAnswer = models.BooleanField(default=False)

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True)


class Comment(models.Model):
    message = models.TextField(verbose_name="コメント",  max_length=2000)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True)

templates/homes/home.html
{% extends 'common/base.html' %}
{% load humanize %}
{% load static %}

{% block title %}電子塾 【ネロレイ】 | 学習特化型Q&Aサイト{% endblock %}

{% block meta %}
<meta name="Description" content="電子塾 【ネロレイ】は学習に特化したQ&amp;Aサイトです。わからない問題について質問すると、他の利用者が回答してくれます。相互に理解を深めましょう。">
<link rel="canonical" href="https://nerorei.com/">
<!--共有時-->
<meta property="og:title" content="電子塾 【ネロレイ】｜学習特化型Q&amp;Aサイト">
<meta property="og:type" content="article">
<meta property="og:description" content="電子塾 【ネロレイ】）は学習に特化したQ&amp;Aサイトです。わからない問題について質問すると、他の利用者が回答してくれます。相互に理解を深めましょう。" />
<meta property="og:image" content="https://nerorei.com/static/images/momiji.png">
<meta property="og:site_name" content="電子塾 【ネロレイ】">
<meta name="twitter:card" content="summary" />
{% endblock %}

<body>
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-9">
            <div class="my-3">
                <ul class="nav nav-tabs" id="topicTag" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link {% if home_nav == 'new' or home_nav is None %}active{% endif %}" id="new-tab"
                           href="{% url 'home_nav' home_nav='new' %}">新着</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if home_nav == 'active' %}active{% endif %}" id="active-tab"
                           href="{% url 'home_nav' home_nav='active' %}">アクティブ</a>
                    </li>
                </ul>

                <div class="tab-content mt-3" id="myTabContent">
                    <div class="tab-pane fade show active" id="new" role="tabpanel" aria-labelledby="new-tab">
                        {% include 'homes/home_support.html' %}
                        {% include 'common/pagination.html' %}
                    </div>
                </div>

            </div>
        </div>
        <div class="col-lg-3">
            <div class="my-3">
                <p style="text-align: center">全ユーザー: {{ users.count }}人</p>
                <table class="table table-dark table-bordered">
                    <thead>
                    <tr>
                        <th class="text-center" scope="col">score</th>
                        <th class="text-center" scope="col">ランキング</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="text-center">
                            {% if user.is_anonymous %}
                            --
                            {% else %}
                            {{ user.score }}
                            {% endif %}
                        </td>
                        <td class="text-center">
                            {% if user.is_anonymous %}
                            --
                            {% else %}
                            {{ user_index }}位
                            {% endif %}
                        </td>
                    </tr>
                    </tbody>
                </table>

                <div class="my-3 p-3" style="background: lightgray">
                    <p>Myタグ</p>
                    <hr>
                    <!--タグを登録していない場合とアノニマスユーザの場合。-->
                    {% if not user.register_tag.all or user.is_anonymous%}
                          タグを登録していません
                    {% else %}
                    {% for tag in user.register_tag.all %}
                        <a class="badge badge-pill badge-primary" href="{% url 'tag_detail' tag.pk %}">
                            <span style="color: white;">{{ tag.name }}</span>
                        </a>
                        {% endfor %}
                    {% endif %}
                    <hr>
                    <p><a href="{% url 'tags:tag_list' %}">タグ一覧へ</a></p>
                </div>

                <div class="my-3 p-3" style="background: whitesmoke">
                    <p>ランキング</p>
                    <hr>
                    <table class="table table-bordered">
                        <tbody>
                        {% for u in users|slice:":10" %}
                        <tr>
                            <td class="text-center">
                                {{ forloop.counter }}
                            </td>
                            <td class="text-center">
                                <a href="{% url 'users:profile_detail' user_pk=u.id %}">
                                    <img src="{{ u.icon.url }}" style="max-width: 25px;"/>
                                </a>
                                <p><a href="{% url 'users:profile_detail' user_pk=u.id %}">
                                    {{ u.username }}
                                </a></p>
                            </td>
                            <td class="text-center">
                                <small>Score</small>
                                <a href="{% url 'users:profile_detail' user_pk=u.id %}">
                                    {{ u.score }}
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <hr>
                    <p><a href="{% url 'users:ranking_list' %}">ランキングをもっと見る</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/homes/home_support.html
{% load humanize %}
<table class="table table-bordered">
    <tbody>
    {% for question in question_list %}
        <tr>
            <td>
                <a href="{% url 'questions:question_detail' question_pk=question.pk %}">{{ question.subject }}</a>
                <small class="text-muted d-block">
                    <a href="{% url 'users:profile_detail' user_pk=question.starter.id %}">
                        <img src="{{ question.starter.icon.url }}" style="max-width: 25px;"/>
                    </a>
                    <a href="{% url 'users:profile_detail' user_pk=question.starter.id %}">
                        {{ question.starter }}
                    </a>
                </small>
            </td>
            <td class="align-middle">
                {% if question.tag %}
                {% for t in question.tag.all %}
                    <a class="badge badge-pill badge-primary"
                       href="{% url 'tags:tag_detail' t.pk %}">
                        <span style="color: white;">{{ t.name }}</span>
                    </a>
                {% endfor %}
                {% endif %}
            </td>
            <td class="align-middle">{{ question.views }}view</td>
            {% if question.has_bestAnser %}
                <td class="align-middle" style="color: orangered">解決済み</td>
            {% else %}
                <td class="align-middle" style="color: grey">回答募集中</td>
            {% endif %}
            {% if home_nav != 'active'%}
                <td class="align-middle">
                    <p>投稿</p>
                    <small>{{ question.created_at|naturaltime }}</small>
                </td>
            {% else %}
                <td class="align-middle">
                    <p>更新</p>
                    <small>{{ question.last_updated|naturaltime }}</small>
                </td>
            {% endif %}
            <td class="align-middle">回答{{ question.get_answers_count }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>