tags/urls.py
from django.urls import path
from . import views

# 実験用
from django.views.generic import TemplateView

app_name = 'tags'

urlpatterns = [
    path('', views.TagListView.as_view(), name='tag_list'),  # タグ一覧メニュー
    path('<int:tag_pk>/', views.TagDetailView.as_view(), name='tag_detail'),# タグ詳細
    path('<int:tag_pk>/<str:tag_nav>/', views.TagDetailView.as_view(), name='tag_nav'), # 詳細の中のナビゲーション部分
]

users/urls.py
from django.urls import path
from . import views
# 実験用
from django.views.generic import TemplateView

app_name = 'users'

urlpatterns = [
    path('setting/profile/', views.ProfileSetting.as_view(), name='profile_setting'),  # プロフィール設定
    path('setting/leave-confirm/', views.LeaveConfirm.as_view(), name='leave_confirm'),  # 退会確認

    path('profile/<int:user_pk>', views.ProfileDetail.as_view(), name='profile_detail'),  # プロフィール詳細
    path('profile/<int:user_pk>/<str:profile_nav>/', views.ProfileDetail.as_view(),
         name='profile_nav'),

    path('<int:user_pk>/connection/', views.Connection.as_view(), name='connection'),

    path('ranking/', views.RankingList.as_view(), name='ranking_list'),
]

questions/models.py
from django.db import models
# markdown用
from django.utils.safestring import mark_safe
from markdown import markdown

from tags.models import Tag
from django.contrib.auth import get_user_model


# questionのモデル
class Question(models.Model):
    subject = models.CharField(max_length=20)
    message = models.TextField(max_length=4000)
    created_at = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    # タグを削除できないようにProtectと指定している。
    tag = models.ManyToManyField(Tag, related_name='question_tag', verbose_name='タグ全て', )

    starter = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True)
    views = models.PositiveIntegerField(default=0)
    has_bestAnser = models.BooleanField(default=False)

    def __str__(self):
        return self.subject

    def get_message_as_markdown(self):
        return mark_safe(markdown(self.message, safe_mode='escape'))

    # 回答数を簡単に得る
    def get_answers_count(self):
        return Answer.objects.filter(question=self).count()


class Answer(models.Model):
    message = models.TextField(verbose_name="回答", max_length=4000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    is_bestAnswer = models.BooleanField(default=False)

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True)


class Comment(models.Model):
    message = models.TextField(verbose_name="コメント",  max_length=2000)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from config.settings.base import AUTH_USER_MODEL
from tags.models import Tag
import os
from django.conf import settings

class CustomUser(AbstractUser):
    class Meta(AbstractUser.Meta):
        db_table = 'custom_user'

    description = models.CharField(verbose_name='自己紹介', max_length=300, blank=True, null=True)

    icon = models.ImageField(verbose_name='アイコン', upload_to='icon/', default='momiji.png')


    follow = models.ManyToManyField(AUTH_USER_MODEL, related_name='custom_user_follow', blank=True)
    register_tag = models.ManyToManyField(Tag, related_name='custom_user_register_tag', blank=True)
    score = models.IntegerField(verbose_name='スコア', default=0)

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm


class ProfileSettingForm(UserChangeForm):
    password = None
    description = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'rows': 5,
                'placeholder': '自己紹介を300文字以内で入力してください。'}
        ),
        max_length=300,
        required=False
    )
    # アイコンボタンの文字変える。imgを出す。
    icon = forms.ImageField(label='アイコン', required=False,
                            widget=forms.FileInput)

    class Meta:
        model = get_user_model()
        fields = ['username', 'icon', 'description']

users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.shortcuts import redirect
from django.urls import reverse_lazy

from django.utils.decorators import method_decorator
from django.views.generic import UpdateView, TemplateView, ListView

from questions.models import Question
from users.forms import ProfileSettingForm


@method_decorator(login_required, name='dispatch')
class ProfileSetting(UpdateView):
    model = get_user_model()
    form_class = ProfileSettingForm
    template_name = 'users/profile_setting.html'
    success_url = reverse_lazy('home')

    # 作った人のみアクセス化
    def get_object(self, *args, **kwargs):
        return get_user_model().objects.get(pk=self.request.user.pk)


@method_decorator(login_required, name='dispatch')
class LeaveConfirm(TemplateView):
    template_name = 'users/leave_confirm.html'

    def post(self, request, *args, **kwargs):
        user = get_user_model().objects.get(pk=self.request.user.pk)
        user.delete()
        return redirect("home")


@method_decorator(login_required, name='dispatch')
class ProfileDetail(ListView):
    model = Question
    paginate_by = 3
    template_name = 'users/profile_detail.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile_nav'] = self.kwargs.get("profile_nav")
        target_user = get_user_model().objects.get(pk=self.kwargs.get('user_pk'))
        if target_user in self.request.user.follow.all():
            is_follow = True
        else:
            is_follow = False
        context['target_user'] = target_user
        context['is_follow'] = is_follow
        return context

    def get_queryset(self):
        profile_nav = self.kwargs.get("profile_nav")
        queryset = None
        user = get_user_model().objects.get(pk=self.kwargs.get('user_pk'))
        if (profile_nav == 'question') or (profile_nav is None):
            queryset = Question.objects.filter(starter=user).order_by('-created_at').annotate(
                replies=Count('answer'))
        elif profile_nav == 'answer':
            queryset = Question.objects.filter(answer__created_by=user).order_by('-created_at').annotate(
                replies=Count('answer'))

        return queryset

    def post(self, request, *args, **kwargs):
        target_user = get_user_model().objects.get(pk=self.kwargs.get('user_pk'))
        if 'do_follow' in request.POST:
            request.user.follow.add(target_user)
            request.user.save()
            return self.get(request, *args, **kwargs)

        elif 'now_follow' in request.POST:
            request.user.follow.remove(target_user)
            request.user.save()
            return self.get(request, *args, **kwargs)


@method_decorator(login_required, name='dispatch')
class Connection(TemplateView):
    template_name = 'users/connection.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        target_user = get_user_model().objects.get(pk=self.kwargs.get('user_pk'))
        context['target_user'] = target_user
        return context


class RankingList(ListView):
    model = get_user_model()
    paginate_by = 50
    template_name = 'users/ranking.html'

    def get_queryset(self):
        queryset = get_user_model().objects.all().order_by('-score')
        return queryset

templates/users/connection.html
{% extends 'common/base.html' %}
{% block title %}{{ viewuser.username }}のフォロー・フォロワー一覧 | 電子塾 【ネロレイ】{% endblock %}

{% block meta %}
<meta name="Description" content="{{ viewuser.username }}のフォロー・フォロワー一覧  | 電子塾 【ネロレイ】は学習に特化したQ&amp;Aサイトです。わからない問題について質問すると、他の利用者が回答してくれます。相互に理解を深めましょう。">
<link rel="canonical" href="https://nerorei.com/users/{{ viewuser.id }}/connection/">
{% endblock %}

{% block content %}
    <div class="container">
        <h5>{{ target_user.username }}のフォロー・フォロワー一覧</h5>

        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="follow-tab" data-toggle="tab" href="#follow" role="tab"
                   aria-controls="follow" aria-selected="true">フォロー</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="follower-tab" data-toggle="tab" href="#follower" role="tab"
                   aria-controls="follower" aria-selected="false">フォロワー</a>
            </li>
        </ul>

        <div class="tab-content mt-3" id="myTabContent">
            <div class="tab-pane fade show active" id="follow" role="tabpanel" aria-labelledby="follow-tab">
                <table class="table">
                    <tbody>
                    {% for follow in target_user.follow.all %}
                        <tr>
                            <td>
                                <a href="{% url 'users:profile_detail' user_pk=follow.id %}">
                                    <img src="{{ follow.icon.url }}" style="max-width: 25px;"/>
                                </a>
                                <a href="{% url 'users:profile_detail' user_pk=follow.id %}">
                                    {{ follow.username }}
                                </a>
                            </td>
                            <td>
                                <span style="color: blue">Q:{{ follow.question_set.count }}</span>
                                <span style="color: orangered">A:{{ follow.answer_set.count }}</span>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="tab-pane fade" id="follower" role="tabpanel" aria-labelledby="follower-tab">
                <table class="table">
                    <tbody>
                    {% for follower in target_user.custom_user_follow.all %}
                        <tr>
                            <td>
                                <a href="{% url 'users:profile_detail' user_pk=follower.id %}">
                                    <img src="{{ follower.icon.url }}" style="max-width: 25px;"/>
                                </a>
                                <a href="{% url 'users:profile_detail' user_pk=follower.id %}">
                                    {{ follower.username }}
                                </a>
                            </td>
                            <td>
                                <span style="color: blue">Q:{{ follower.question_set.count }}</span>
                                <span style="color: orangered">A:{{ follower.answer_set.count }}</span>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/leave_confirm.html
{% extends 'common/base.html' %}

{% block title %}退会申請 | 電子塾 【ネロレイ】{% endblock %}

{% block meta %}
<meta name="Description" content="退会申請 | 電子塾 【ネロレイ】は学習に特化したQ&amp;Aサイトです。わからない問題について質問すると、他の利用者が回答してくれます。相互に理解を深めましょう。">
{% endblock %}

{% block content %}
    <div class="container py-3">
        <h3 class="py-3">退会申請</h3>
        <div class="p-3"
             style="background: gray;">
            退会処理を行うと、プロフィール情報、score、質問・回答などが全て削除されます。
            ご注意をお願いします。
        </div>

        <form action="{% url 'users:leave_confirm'%}" method="post" class="mb-4 mt-4">
            {% csrf_token %}
            <button name="followchu" type="submit" class="btn btn-danger">
                退会する
            </button>
        </form>

    </div>

{% endblock %}

templates/users/profile_detail.html
{% extends 'common/base.html' %}
{% load static %}

{% block title %}{{ target_user.username }}のプロフィール | 電子塾 【ネロレイ】{% endblock %}

{% block meta %}
<meta name="Description" content="{{ target_user.username }} | 電子塾 【ネロレイ】は学習に特化したQ&amp;Aサイトです。わからない問題について質問すると、他の利用者が回答してくれます。相互に理解を深めましょう。">
<link rel="canonical" href="https://nerorei.com/{{ target_user.id }}/">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="card bg-light mt-5">
            <img class="card-img-top pt-4" src="{{ target_user.icon.url }}" alt="{{ target_user.username }}"
                 style="width: 150px; margin: 0 auto"/>
            <div class="card-body ">
                <h4 class="card-title text-center">{{ target_user.username }}</h4>
                {% if  target_user.description != None %}
                    <p>{{ target_user.description }}</p>
                {% endif %}

            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item text-center">
                    フォロー {{ target_user.follow.count }}　フォロワー{{ target_user.custom_user_follow.count }}
                    <a href="{% url 'users:connection' user_pk=target_user.pk %}">　一覧へ</a>
                </li>
                <li class="list-group-item text-center">
                    登録タグ<br>
                    {% for tag in target_user.register_tag.all %}
                        <a class="badge badge-pill badge-primary" href="{% url 'tag_detail' tag.pk %}">
                            <span style="color: white;">{{ tag.name }}</span>
                        </a>
                    {% endfor %}
                </li>
                {% if  target_user.id == user.id %}
                    <li class="list-group-item text-center">
                        <a class="btn btn-secondary" href="{% url 'users:profile_setting'%}">プロフィール編集する</a>
                    </li>
                {% else %}
                    {% if is_follow %}
                        <li class="list-group-item text-center">
                            <form method="post" class="mb-4 mt-4">
                                {% csrf_token %}
                                <button name="now_follow" type="submit" class="btn btn-primary">
                                    フォロー中
                                </button>
                            </form>
                        </li>
                    {% else %}
                        <li class="list-group-item text-center">
                            <form method="post" class="mb-4 mt-4">
                                {% csrf_token %}
                                <button name="do_follow" type="submit" class="btn btn-primary">
                                    フォローする
                                </button>
                            </form>
                        </li>
                    {% endif %}
                {% endif %}
            </ul>
        </div>

        <ul class="nav nav-tabs" id="topicTag" role="tablist">
            <li class="nav-item">
                <a class="nav-link {% if profile_nav == 'question' or profile_nav is None %}active{% endif %}" id="new-tab"
                   href="{% url 'users:profile_nav' user_pk=target_user.pk profile_nav='question' %}">質問</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if profile_nav == 'answer' %}active{% endif %}" id="active-tab"
                   href="{% url 'users:profile_nav' user_pk=target_user.pk profile_nav='answer' %}">回答</a>
            </li>
        </ul>
        <div class="tab-content mt-3" id="myTabContent">
            <div class="tab-pane fade show active" id="new" role="tabpanel" aria-labelledby="new-tab">
                {% include 'homes/home_support.html' %}
                {% include 'common/pagination.html' %}
            </div>
        </div>


    </div>
{% endblock %}

{% block javascript %}

{% endblock %}

templates/users/profile_setting.html
{% extends 'common/base.html' %}
{% load widget_tweaks %}

{% block title %}プロフィール設定 | 電子塾 【ネロレイ】{% endblock %}

{% block meta %}
<meta name="Description" content="プロフィール設定 | 電子塾 【ネロレイ】は学習に特化したQ&amp;Aサイトです。わからない問題について質問すると、他の利用者が回答してくれます。相互に理解を深めましょう。">
<link rel="canonical" href="https://nerorei.com/users/setting/profile/">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row m-2">
            <div class="col-lg-8">
                <h5>プロフィール設定</h5>
                <form method="post" enctype="multipart/form-data" novalidate>
                    {% csrf_token %}
                    <div class="form-group m-2">
                        {% if form.is_bound %}
                            {% if form.username.errors %}
                                {% render_field form.username class="form-control is-invalid" %}
                                {% for error in form.username.errors %}
                                    <div class="invalid-feedback">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            {% else %}
                                {% render_field form.username class="form-control is-valid" %}
                            {% endif %}
                        {% else %}
                            <label>ユーザー名:</label>
                            {% render_field form.username class="form-control" %}
                        {% endif %}
                    </div>

                    <div class="form-group m-2">
                        {% if form.is_bound %}
                            {% if form.icon.errors %}
                                {% render_field form.icon class="form-control is-invalid" %}
                                {% for error in form.icon.errors %}
                                    <div class="invalid-feedback">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            {% else %}
                                {% render_field form.icon class="form-control is-valid" %}
                            {% endif %}
                        {% else %}
                            <img src="{{ customuser.icon.url }}" width=40px/>
                            <label>アイコンの変更:</label>
                            {% render_field form.icon class="form-control" %}
                        {% endif %}
                    </div>

                    <div class="form-group m-2">
                        {% if form.is_bound %}
                            {% if form.description.errors %}
                                {% render_field form.description class="form-control is-invalid" %}
                                {% for error in form.description.errors %}
                                    <div class="invalid-feedback">
                                        {{ error }}
                                    </div>
                                {% endfor %}
                            {% else %}
                                {% render_field form.description class="form-control is-valid" %}
                            {% endif %}
                        {% else %}
                            <label>自己紹介:</label>
                            {% render_field form.description class="form-control" %}
                        {% endif %}
                    </div>
                    <button type="submit" class="btn btn-primary btn-block mb-3">保存</button>
                </form>
            </div>
            <div class="col-lg-4">
                <div class="list-group m-3">
                    <a href="{% url 'account_change_password' %}"
                       class="list-group-item list-group-item-action">パスワード設定</a>
                    <a href="{% url 'account_email' %}"
                       class="list-group-item list-group-item-action">メールアドレス設定</a>
                    <a href="{% url 'users:leave_confirm'%}"
                       class="list-group-item list-group-item-action">退会する</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/users/ranking.html
{% extends 'common/base.html' %}
{% block title %}ランキング一覧 | 電子塾 【ネロレイ】{% endblock %}

{% block meta %}
<meta name="Description" content="ランキング一覧 | 電子塾 【ネロレイ】は学習に特化したQ&amp;Aサイトです。わからない問題について質問すると、他の利用者が回答してくれます。相互に理解を深めましょう。">
<link rel="canonical" href="https://nerorei.com/users/ranking/">
{% endblock %}

{% block content %}
<div class="container">
    <h5>ランキング一覧</h5>
    <table class="table">
        <tbody>
        {% for user in object_list %}
        <tr>
            <td class="text-center">
                {{ forloop.counter }}
            </td>
            <td class="text-center">
                <a href="{% url 'users:profile_detail' user_pk=user.id %}">
                    <img src="{{ user.icon.url }}" style="max-width: 25px;"/>
                </a>
            </td>
            <td class="text-center">
                <a href="{% url 'users:profile_detail' user_pk=user.id %}">
                    {{ user.username }}
                </a>
            </td>
            <td class="text-center">
                <small>Score</small>
                <a href="{% url 'users:profile_detail' user_pk=user.id %}">
                    {{ user.score }}
                </a>
            </td>
            <td class="text-center">
                <span style="color: blue">Q:{{ user.question_set.count }}</span>
                <span style="color: orangered">A:{{ user.answer_set.count }}</span>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}